<a href="https://colab.research.google.com/github/daquarti/AI/blob/main/Bidireccional_LSTM_medical_history.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import sys
sys.path.append('/content/drive/My Drive/NLP/antecedentes')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
import tensorflow as tf

In [ ]:
 print(tf.__version__) 

2.2.0


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import numpy as np
import pandas as pd


In [ ]:
path = '/content/drive/My Drive/NLP/'

In [ ]:
df = pd.read_csv (path + 'dataframe_antecedente_con_fake_16_4.csv')

In [ ]:
df.etiqueta.nunique()

67

In [ ]:
y = pd.get_dummies(df.etiqueta, prefix='etiqueta')

In [ ]:
Y = y.values

In [ ]:
labels = y.columns

In [ ]:
Y.shape

(1390, 67)

In [ ]:
df.columns

Index(['frase', 'etiqueta'], dtype='object')

In [ ]:
X = df.frase

In [ ]:
X[0]

'paciente con antecedentes de DLP'

In [ ]:
max_words = 10
max_len = 100
embedding_dim = 20

In [ ]:
X_train_str = X

In [ ]:
tokenizer = tf.keras.preprocessing.text.Tokenizer(lower=True)
tokenizer.fit_on_texts(X_train_str)
X_train_tokenizer = tokenizer.texts_to_sequences(X_train_str)
X_train_padding = tf.keras.preprocessing.sequence.pad_sequences(X_train_tokenizer, maxlen=max_len)

In [ ]:
X[1] 

'DLP'

In [ ]:
X_train_tokenizer[1]

[365]

In [ ]:
X_train_padding[1]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0, 365], dtype=int32)

In [ ]:
import numpy as np

In [ ]:
#Test Glove, ...
embeddings_index = {}
f = open('/content/drive/My Drive/NLP/antecedentes/models/myModel.txt', 'r', encoding='utf-8')
for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:], dtype='float32')
    embeddings_index[word] = coefs
f.close()

In [ ]:
embeddings_index['hipertenso']

array([ 0.7870297 , -0.10730695, -0.05153625, -0.6942336 , -0.03404878,
        0.14566395, -1.2079111 , -0.2572584 ,  0.28956375,  0.48448113,
        0.24335562, -0.47889775,  0.14352533, -0.55999714, -0.6780637 ,
        0.35730138,  0.98991364, -0.1994929 , -0.29496998,  0.28248915],
      dtype=float32)

In [ ]:

embeddings_index.get ("domicilio")

array([-0.0611829 ,  0.24114676,  0.6524052 , -0.883787  , -0.05411399,
        0.9299469 ,  0.03504966,  0.07336997, -0.2669357 ,  0.30790618,
       -0.8039609 , -0.18684183,  0.11913169, -1.103894  ,  0.01974086,
        0.16738011, -0.6943712 ,  0.44728225, -0.15371116,  0.6344526 ],
      dtype=float32)

In [ ]:
word_index = tokenizer.word_index
num_words = max(max_words, len(word_index) + 1)
embedding_matrix = np.zeros((num_words, embedding_dim), dtype='float32')
for word, i in word_index.items():
    if i >= max_words:
        continue
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector
    else:
      print (word)

In [ ]:
embedding_matrix[1]

array([ 0.46234336,  0.26877093,  0.28479466, -0.75451916, -0.75162154,
       -0.08058153, -0.40510598,  0.11838973, -1.0390542 , -0.42800787,
        0.14885536, -0.17817041,  0.12438817, -0.6117846 ,  0.16640706,
       -0.13367772,  0.5405224 , -0.03378943,  0.18248585,  1.1382024 ],
      dtype=float32)

In [ ]:
for key, v in word_index.items():    
    if v == 200:
        print(key)

angina


In [ ]:
len(word_index.items())

1142

Read about tf.keras.layers.Embedding:

https://blog.keras.io/using-pre-trained-word-embeddings-in-a-keras-model.html

https://stats.stackexchange.com/questions/270546/how-does-keras-embedding-layer-work

In [ ]:
input = tf.keras.layers.Input(shape=(max_len,))
x = tf.keras.layers.Embedding(1143, embedding_dim, weights=[embedding_matrix], trainable=False)(input)

Read about Bidirectional GRU/LSTM

https://hackernoon.com/multilayer-bidirectional-lstm-gru-for-text-summarization-made-easy-tutorial-4-a63db108b44f

In [ ]:
x = tf.keras.layers.Bidirectional(tf.keras.layers.GRU(800, return_sequences=True))(x)

In [ ]:
x = tf.keras.layers.Conv1D(64, kernel_size=3, padding="valid", kernel_initializer="glorot_uniform")(x)

Archiquecture notes: 

https://stackoverflow.com/questions/45563438/hybrid-of-max-pooling-and-average-pooling

https://books.google.fr/books?id=-F3SDwAAQBAJ&pg=PA80&lpg=PA80&dq=averagepol+%2B+maxpool+%2B+concatenate&source=bl&ots=w-7eWgfixz&sig=ACfU3U2Q6aY32vhreumAKYc5zv5FZzaOTg&hl=en&sa=X&ved=2ahUKEwiplsWprIjoAhULzoUKHVhaD2kQ6AEwAnoECAgQAQ#v=onepage&q&f=false

In [ ]:
avg_pool = tf.keras.layers.GlobalAveragePooling1D()(x)
max_pool = tf.keras.layers.GlobalMaxPooling1D()(x)
x = tf.keras.layers.concatenate([avg_pool, max_pool])

In [ ]:
preds = tf.keras.layers.Dense(67, activation="softmax")(x)
model = tf.keras.Model(input, preds)
model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 100)]        0                                            
__________________________________________________________________________________________________
embedding (Embedding)           (None, 100, 20)      22860       input_1[0][0]                    
__________________________________________________________________________________________________
bidirectional (Bidirectional)   (None, 100, 1600)    3945600     embedding[0][0]                  
__________________________________________________________________________________________________
conv1d (Conv1D)                 (None, 98, 64)       307264      bidirectional[0][0]              
______________________________________________________________________________________________

Read about metrics

https://stats.stackexchange.com/questions/233275/multilabel-classification-metrics-on-scikit

In [ ]:
model.compile(loss='CategoricalCrossentropy', optimizer=tf.keras.optimizers.Adam(lr=1e-3), metrics=['accuracy'])

In [ ]:
model.fit(X_train_padding, Y, batch_size=64,
          epochs=10, verbose=1)

Epoch 1/10
22/22 [==============================] - 77s 4s/step - loss: 2.5915 - accuracy: 0.2820
Epoch 2/10
22/22 [==============================] - 77s 3s/step - loss: 2.5672 - accuracy: 0.2748
Epoch 3/10
22/22 [==============================] - 77s 3s/step - loss: 2.5707 - accuracy: 0.2777
Epoch 4/10
22/22 [==============================] - 77s 3s/step - loss: 2.5775 - accuracy: 0.2820
Epoch 5/10
22/22 [==============================] - 78s 4s/step - loss: 2.5744 - accuracy: 0.2763
Epoch 6/10
22/22 [==============================] - 78s 4s/step - loss: 2.5797 - accuracy: 0.2741
Epoch 7/10
22/22 [==============================] - 77s 4s/step - loss: 2.5804 - accuracy: 0.2799
Epoch 8/10
22/22 [==============================] - 77s 4s/step - loss: 2.5778 - accuracy: 0.2719
Epoch 9/10
22/22 [==============================] - 77s 4s/step - loss: 2.5724 - accuracy: 0.2763
Epoch 10/10
22/22 [==============================] - 77s 3s/step - loss: 2.5631 - accuracy: 0.2777


In [ ]:
X_train[1]

array([15,  1,  9, 58, 49,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
      dtype=int32)

In [ ]:
np.expand_dims(X_train[1], 0).shape

(1, 100)

In [ ]:
tokenizer = tf.keras.preprocessing.text.Tokenizer(lower=True)
tokenizer.fit_on_texts(X_train_str)

In [ ]:
X_train_test = tokenizer.texts_to_sequences(['acv'])

In [ ]:
X_train_test

[[155]]

In [ ]:
X_train_padding_test = tf.keras.preprocessing.sequence.pad_sequences(X_train_test, maxlen=max_len)

In [ ]:
predictions = model.predict(X_train_padding_test)

In [ ]:
resultado = predictions[0]

In [ ]:
labela = y.columns

In [ ]:
fusion = zip(labela, resultado)
dictionary = dict(fusion)

In [ ]:
dictionary

{'etiqueta_ACV': 0.012588305,
 'etiqueta_AIT': 0.012132571,
 'etiqueta_ATC con stent': 0.027682118,
 'etiqueta_Alergia': 0.025285495,
 'etiqueta_Asma': 0.012379086,
 'etiqueta_CA mama': 0.00650299,
 'etiqueta_CRM': 0.011581504,
 'etiqueta_Celiaquía': 0.01607277,
 'etiqueta_Chagas': 0.009397269,
 'etiqueta_Colon irritable': 0.008058524,
 'etiqueta_Convulsiones-epilepsia': 0.03487521,
 'etiqueta_DBT': 0.019857822,
 'etiqueta_DLP': 0.020352716,
 'etiqueta_Demencia': 0.006157337,
 'etiqueta_Divertículos': 0.009106306,
 'etiqueta_Diálisis': 0.008672727,
 'etiqueta_EPOC': 0.0059596226,
 'etiqueta_Gastritis': 0.0141546745,
 'etiqueta_HIV': 0.008881322,
 'etiqueta_HTA': 0.014201869,
 'etiqueta_Hepatitis': 0.017746547,
 'etiqueta_IAM': 0.019816913,
 'etiqueta_ICC': 0.018288577,
 'etiqueta_IRC': 0.027862862,
 'etiqueta_Litiasis vesicular': 0.006817354,
 'etiqueta_Meningitis': 0.028517507,
 'etiqueta_Neumonía': 0.015735164,
 'etiqueta_Obesidad': 0.018124985,
 'etiqueta_Pacientes con trasplante de

In [ ]:
dict_ordenado = sorted(dictionary.items(), key=lambda x: x[1], reverse=True)

In [ ]:
dict_ordenado

[('etiqueta_arritmia', 0.0533651),
 ('etiqueta_TBQ', 0.039421152),
 ('etiqueta_Convulsiones-epilepsia', 0.03487521),
 ('etiqueta_alteraciones del flujo vaginal', 0.03273762),
 ('etiqueta_valvulopatía', 0.030908752),
 ('etiqueta_Meningitis', 0.028517507),
 ('etiqueta_IRC', 0.027862862),
 ('etiqueta_ATC con stent', 0.027682118),
 ('etiqueta_hipotiroidismo', 0.027249787),
 ('etiqueta_Alergia', 0.025285495),
 ('etiqueta_prostatismo', 0.022619065),
 ('etiqueta_leucemia/linfoma', 0.022290587),
 ('etiqueta_enfermedad coronaria', 0.020476744),
 ('etiqueta_DLP', 0.020352716),
 ('etiqueta_DBT', 0.019857822),
 ('etiqueta_IAM', 0.019816913),
 ('etiqueta_anticoagulado', 0.01926852),
 ('etiqueta_ICC', 0.018288577),
 ('etiqueta_Obesidad', 0.018124985),
 ('etiqueta_Hepatitis', 0.017746547),
 ('etiqueta_artrosis', 0.01635482),
 ('etiqueta_RGE', 0.016342444),
 ('etiqueta_Celiaquía', 0.01607277),
 ('etiqueta_depresión', 0.015898045),
 ('etiqueta_Neumonía', 0.015735164),
 ('etiqueta_lipotimia', 0.01565617

TODO ver1

1.Dataset split into train/test

2.Little play tuning (batch_size, epochs,..)

3.Try another metrics





In [ ]:
labels = y.columns.to_list()

In [ ]:
def predict (frase):
  frase = [frase]
  frase_tokenizer = tokenizer.texts_to_sequences(frase)
  X_frase_padding = tf.keras.preprocessing.sequence.pad_sequences(frase_tokenizer, maxlen=max_len)
  predictions = model.predict(X_frase_padding)
  pred = predictions.tolist()
  pred = pred[0]
  dic = dict(zip(labels, pred))
  sorted(dic.items(), key=lambda x: x[1], reverse=True)
  for key, proba in dic.items(): 
    if proba >0.30:
        print(key)


In [ ]:
print (predict ('paciente hipertenso'))

None
